services:
  db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_USER: good
      POSTGRES_PASSWORD: boy
      POSTGRES_DB: db
    ports:
      - "5002:5432"
    volumes:
      - /Users/varun/documents/db_volumes/auth-service-db:/var/lib/postgresql
    networks:
      - internalpatient

networks:
  internalpatient:
    external: true