services:
  billing-service:
    container_name: billing-service
    image: billing-service:latest
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internalpatient

networks:
  internalpatient:
    external: true
